### ISSUE TITLE
Did @riotjs/register stop exporting `register` ?

### ISSUE THREAD

**Issue by nibushibu** [riot/register#2]
Hi!
Thank you for your hard work in responding to the major version upgrade!

Well, I have recently tried v9 myself.
I noticed that if I try to import register from @riotjs/register in node.js, it will throw an error as follows.

```bash
> node node_scripts/html.js

file:///Users/genki/Sites/Getup/node_scripts/html.js:6
import register from '@riotjs/register'
         ^^^^^^^^
SyntaxError: The requested module '@riotjs/register' does not provide an export named 'register'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.17.1
ERROR: "html-from-riot" exited with 1.
ERROR: "html" exited with 1.
```

and here is the file I ran.
https://github.com/nibushibu/Getup/blob/d79644794d0f6869de8f39b90ff5a39ca3c632ed/node_scripts/html.js#L6

I am continuing to work on solving my problem, but I would appreciate any tips you can give me.

**Comment by GianlucaGuarini** [comment]
Hi @nibushibu in v9 I have dropped the support for commonjs projects so you will not be able to import Riot components in that way. If you want to migrate your project using modern nodejs syntax with esm modules you will need to call your scripts [registering the riot loader](https://plnkr.co/edit/3wWRvhDsDy5MWrXR). For example in your `package.json`:

```json
{
  "type": "module",
  "scripts": {
    "start": "node --loader @riotjs/register app.js"
  }
}
```

If you want to keep using commonjs syntax the older `@riotjs/register` version should just be fine and you don't need to update it.

**Comment by nibushibu** [comment]
@GianlucaGuarini Thank you for your reply and advice!  Finally I was able to solve the problem at hand ✨
