### ISSUE TITLE
Is it possible to make it possible to import files with extensions other than .riot?

### ISSUE THREAD

**Issue by nibushibu** [riot/register#3]
As far as I understand, only the `.riot` extension can currently be imported using `riot/register`, but are there any plans to add some option to import files with other extensions?

(I often use `.html` extensions for my riot files, and would like to import `.html` in the future if possible.)

**Comment by GianlucaGuarini** [comment]
We could use the [initialize function](https://nodejs.org/api/module.html#hooks) to define custom file extensions.
Would you mind opening a PR to add this feature? Thanks

**Comment by GianlucaGuarini** [comment]
@nibushibu I will have a look at it asap. Thank you for your feedback!

**Comment by GianlucaGuarini** [comment]
This feature was added in @riotjs/register@9.1.0 https://github.com/riot/register?tab=readme-ov-file#custom-file-extensions

**Comment by nibushibu** [comment]
Wow, Thanks a lot!!
